### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by kug828** [myparkmk/github-using-exercise#26]
void blockcmp(void)
{
	long long int file1 = (long long)stat1.st_blocks;
	long long int file2 = (long long)stat2.st_blocks;

	if(fil1>file2) printf("text1 is bigger\n");
	else if(file1<file2) printf("text2 is bigger\n");
	else printf("same blocksize\n");

}

long long 으로 받아와서 비교하여 출력합니다.

**Comment by myparkmk** [comment]
잘짜셧네요

**Comment by Jujungin** [comment]
좋아용
