### ISSUE TITLE
file 관련 함수

### ISSUE THREAD

**Issue by Jujungin** [myparkmk/github-using-exercise#35]
struct stat 에 포함된 함수
st_dev 장치 파일의 위치 
, st_ino 파일의 inode 번호
, st_mode 파일의 모드
, st_nlink 파일의 하드링크 수
, st_uid 유저 ID
, st_gid 그룹 ID
, st_rdev 장치의 inode
, st_size 파일의 사이즈
, st_blksize 블럭 사이즈
, st_blocks 블럭 수
, st_atime, st_mtime, st_xtime 시간 stat 

위의 함수를 가지고 struct stat 변수를 stat1과 stat2를 선언하여 저장 가능하다.

**Comment by myparkmk** [comment]
그중 st_mtime 은 파일이 수정된 시간을 알 수 있습니다 하하
